In [1]:
import pandas as pd

link="http://cape.fcfm.buap.mx/cruz-suarez/Data/INEGI/SDEMT225/ENOE_SDEMT325.csv"
data=pd.read_csv(link, encoding="latin1")

In [2]:
data.head()

,r_def,cve_loc,cve_mun,est,est_d_tri,est_d_men,cve_ageb,t_loc_tri,t_loc_men,cd_a,...,t_tra,emp_ppal,tue_ppal,trans_ppal,mh_fil2,mh_col,sec_ins,tipo,mes_cal,cvegeo
0,0,,37,20,808,808,0,1,1,1,...,0,0,0,0,0,0,0,1,7,15037
1,0,,49,30,926,926,0,2,2,3,...,1,2,2,0,3,6,2,1,7,19049
2,0,,49,30,926,926,0,2,2,3,...,0,0,0,0,0,0,0,1,7,19049
3,0,,114,40,976,976,0,1,1,4,...,1,1,2,0,3,1,2,1,9,21114
4,0,,114,10,973,973,0,1,1,4,...,1,1,2,0,2,1,9,1,9,21114

In [3]:
data.shape

(422306, 115)

In [4]:
data.columns.tolist()

['r_def',
 'cve_loc',
 'cve_mun',
 'est',
 'est_d_tri',
 'est_d_men',
 'cve_ageb',
 't_loc_tri',
 't_loc_men',
 'cd_a',
 'cve_ent',
 'con',
 'upm',
 'd_sem',
 'n_pro_viv',
 'v_sel',
 'n_hog',
 'h_mud',
 'n_ent',
 'per',
 'n_ren',
 'c_res',
 'par_c',
 'sex',
 'eda',
 'nac_dia',
 'nac_mes',
 'nac_anio',
 'l_nac_c',
 'cs_p12',
 'cs_p13_1',
 'cs_p13_2',
 'cs_p14_c',
 'cs_p15',
 'cs_p16',
 'cs_p17',
 'n_hij',
 'e_con',
 'cs_p20a_1',
 'cs_p20a_c',
 'cs_p20b_1',
 'cs_p20b_c',
 'cs_p20c_1',
 'cs_ad_mot',
 'cs_p21_des',
 'cs_ad_des',
 'cs_nr_mot',
 'cs_p23_des',
 'cs_nr_ori',
 'ur',
 'zona',
 'salario',
 'fac_tri',
 'fac_men',
 'clase1',
 'clase2',
 'clase3',
 'pos_ocu',
 'seg_soc',
 'rama',
 'c_ocu11c',
 'ing7c',
 'dur9c',
 'emple7c',
 'medica5c',
 'buscar5c',
 'rama_est1',
 'rama_est2',
 'dur_est',
 'ambito1',
 'ambito2',
 'tue1',
 'tue2',
 'tue3',
 'busqueda',
 'd_ant_lab',
 'd_cexp_est',
 'dur_des',
 'sub_o',
 's_clasifi',
 'remune2c',
 'pre_asa',
 'tip_con',
 'dispo',
 'nodispo',
 'c_inac5c',
 'pnea_est',
 'niv_ins',
 'eda5c',
 'eda7c',
 'eda12c',
 'eda19c',
 'hij5c',
 'domestico',
 'anios_esc',
 'hrsocup',
 'ingocup',
 'ing_x_hrs',
 'tpg_p8a',
 'tcco',
 'cp_anoc',
 'imssissste',
 'ma48me1sm',
 'p14apoyos',
 'scian',
 't_tra',
 'emp_ppal',
 'tue_ppal',
 'trans_ppal',
 'mh_fil2',
 'mh_col',
 'sec_ins',
 'tipo',
 'mes_cal',
 'cvegeo']

In [2]:
datos = data[data["emp_ppal"].isin([1, 2])].copy()
datos["sexo"] = datos["sex"].map({'1': "Hombre", '2': "Mujer"})
datos["empleo"] = datos["emp_ppal"].map({1: "Informal", 2: "Formal"})
datos[["sexo", "empleo"]].head()

      sexo    empleo
1   Hombre    Formal
3    Mujer  Informal
4    Mujer  Informal
5   Hombre    Formal
10   Mujer    Formal

In [8]:
muestra = datos.sample(10, replace=True)
muestra.dropna()

,r_def,cve_loc,cve_mun,est,est_d_tri,est_d_men,cve_ageb,t_loc_tri,t_loc_men,cd_a,...,tue_ppal,trans_ppal,mh_fil2,mh_col,sec_ins,tipo,mes_cal,cvegeo,sexo,empleo
78408,0,,3,30,572,572,0,1,1,42,...,1,0,1,1,8,1,7,4003,Hombre,Informal
417655,0,,14,30,1001,1001,0,1,1,36,...,2,0,3,2,2,1,7,22014,Hombre,Formal
331221,0,,56,40,1233,1233,0,1,1,32,...,2,0,3,2,5,1,9,32056,Hombre,Formal
261305,0,,20,30,713,713,0,1,1,5,...,2,0,3,2,2,1,8,11020,Hombre,Formal
25352,0,,114,20,974,974,0,1,1,4,...,1,0,1,1,8,1,9,21114,Hombre,Informal
405710,0,,1,20,502,502,0,1,1,14,...,2,0,3,2,2,1,9,1001,Hombre,Formal
265968,0,,2,20,1148,1148,0,3,3,39,...,1,0,1,7,8,1,8,29002,Hombre,Informal
289557,0,,89,20,637,637,0,1,1,52,...,1,0,1,1,8,1,9,7089,Mujer,Informal
23242,0,,10,10,577,577,0,3,3,84,...,1,0,1,1,8,1,7,4010,Mujer,Informal
124937,0,,64,30,842,842,0,3,3,84,...,1,0,1,7,8,1,7,15064,Mujer,Informal

In [3]:
tabla_empleo=pd.crosstab(datos["empleo"], datos["sexo"], normalize=True)
tabla_empleo

sexo        Hombre     Mujer
empleo
Formal    0.282538  0.195857
Informal  0.301445  0.220160

In [ ]:
marginal_sexo = tabla_empleo.sum(axis=0)
print(marginal_sexo)
tabla_empleo.div(marginal_sexo, axis=1) # condicional respecto al sexo, probabilidad de empleo formal dado que es hombre

sexo
Hombre    0.583982
Mujer     0.416018
dtype: float64

sexo        Hombre     Mujer
empleo
Formal    0.483812  0.470791
Informal  0.516188  0.529209

In [ ]:
marginal_empleo = tabla_empleo.sum(axis=1)
print(marginal_empleo)
tabla_empleo.div(marginal_empleo, axis=0)  # condicional respecto al trabajo,  probabilidad que sea hombre dado que tiene empleo formal

empleo
Formal      0.478395
Informal    0.521605
dtype: float64

sexo        Hombre     Mujer
empleo
Formal    0.590595  0.409405
Informal  0.577918  0.422082

In [11]:
from scipy.stats import norm

n = 9
sigma = 1

l = (0.3*(n)**(1/2))/sigma

res = norm.cdf(l)-norm.cdf(-l)
res

np.float64(0.6318797493064809)

In [14]:
r = norm.ppf(0.975)

In [15]:
n_nueva = (1.96*sigma/0.3)**2
n_nueva

42.684444444444445

In [16]:
from scipy.stats import chi2

l1 = chi2.ppf(0.05,9)
l2 = chi2.ppf(0.95,9)

print(l1,l2)

3.325112843066815 16.918977604620448

In [17]:
b1 = (l1 * sigma**2) / (n-1)
b2 = (l2 * sigma**2) / (n-1)

print(b1,b2,b1-b2)

0.41563910538335186 2.114872200577556 -1.699233095194204

In [ ]:
from scipy.stats import norm, chi2, t, f

t.cdf(2, df=5) - t.cdf(-2, df=5)

f.ppf(0.95, dfn = 5, dfd = 9)