## 2 Probabilidad Condicional

### 2.1 Definición

### Dado un espacio de probabilidad $(\Omega, \mathcal{F}, \mathbb{P})$ y sea $B\in \mathcal{F}$ con $\mathbb{P}(B)>0$. Definimos la probabilidad condicional dado el evento $B$, como $$\mathbb{P}(A|B)=\frac{\mathbb{P}(A\cap B)}{\mathbb{P}(B)}.$$

### 2.1.1 Ejemplo

In [3]:
import pandas as pd
import numpy as np

data=pd.DataFrame({'genero': np.repeat(np.array(['Masculino', 'Femenino']), 150),
                   'deporte': np.repeat(np.array(['Béisbol', 'Basket', 'Americano','Soccer', 
                                                  'Béisbol', 'Basket', 'Americano', 'Soccer']), 
                                                   (34, 40, 58, 18, 34, 52, 20, 44))})

data.head()

      genero  deporte
0  Masculino  Béisbol
1  Masculino  Béisbol
2  Masculino  Béisbol
3  Masculino  Béisbol
4  Masculino  Béisbol

In [4]:
data.tail()

       genero deporte
295  Femenino  Soccer
296  Femenino  Soccer
297  Femenino  Soccer
298  Femenino  Soccer
299  Femenino  Soccer

### Una tabla de contingencia es una herramienta utilizada en la rama de la estadística, la cual consiste en crear al menos dos filas y dos columnas para representar datos categóricos en términos de conteos de frecuencia. Esta herramienta, que también se conoce como tabla cruzada o como tabla de dos vías, tiene el objetivo de representar en un resumen, la relación entre diferentes variables categóricas.

In [2]:
tabla = pd.crosstab(index=data['genero'], columns=data['deporte'], margins=True)
tabla

deporte    Americano  Basket  Béisbol  Soccer  All
genero
Femenino          20      52       34      44  150
Masculino         58      40       34      18  150
All               78      92       68      62  300

### Calcular la probabilidad de seleccionar a un individuo de la población encuestada del genero másculino dado que prefiere el béisbol.

Evento B (es el supuesto) que le guste beisbol, A que sea hombre

In [3]:
tabla.loc['Masculino', 'Béisbol']/tabla.loc['All', 'Béisbol']

np.float64(0.5)

### Calcular la probabilidad de que prefiera basket dado que el individuo es del genero femenino.

B supuesto, que sea femenino, A que le guste basket

In [4]:
tabla.loc['Femenino', 'Basket']/tabla.loc['Femenino', 'All']

np.float64(0.3466666666666667)

## 2.2 Regla de Probabilidad Condicional

### Las siguientes reglas son de gran ayuda en el cálculo de probabilidades condicionales:
### 1. Regla del producto $$\mathbb{P}(A_1\cap A_2\cap...\cap A_n)=\mathbb{P}(A_n|A_1\cap \ldots \cap A_{n-1})\mathbb{P}(A_{n-1}|A_1\cap \ldots \cap A_{n-2})\ldots \mathbb{P}(A_2|A_1)\mathbb{P}(A_1)$$

### 2. Regla de la Probabilidad Total $$\mathbb{P}(B)=\sum_{i=1}^{n}\mathbb{P}(B|A_i)\mathbb{P}(A_i)$$

### 3. Regla de Bayes $$\mathbb{P}(A_i|B)=\frac{\mathbb{P}(B|A_i)\mathbb{P}(A_i)}{\sum_{i=1}^{n}\mathbb{P}(B|A_i)\mathbb{P}(A_i)}$$

La reglas 2 y 3 están relacionadas, de la 2 se puede sacar la 3

## Ejemplo 2.2.1

### Tres máquinas de cierta planta de ensamble, $A_1,A_2, A_3,$ montan $30\%, 45\%, 25\%$ de los productos, respectivamente. Se sabe por experiencia que $2\%,3\%, 2\%$ de los productos ensamblados por cada máquina, respectivamente, tienen defectos. Ahora bien, supóngase que se selecciona de forma aleatoria un producto terminado. ¿Cuál es la probabilidad de que esté defectuoso?

In [5]:
P_A = [0.30, 0.45, 0.25]
P_D_dado_A = [0.02, 0.03, 0.02]

In [ ]:
sum(P_A[i] * P_D_dado_A[i] for i in range(len(P_A))) #la regla de la probabilidad total, 2

0.0245

### si se elige al azar un producto y se encuentra que es defectuoso ¿cuál es la probabilidad de que este ensamblado por la máquina $A_3$?

In [7]:
(P_A[2] * P_D_dado_A[2]) / (sum(P_A[i] * P_D_dado_A[i] for i in range(len(P_A)))) #regla de bayes, la 3
#una forma de actualizar la probabilidad

0.20408163265306123

## Tarea 2.2.2

### Supóngase que en cierta población el $1\%$ de las personas padece una enfermedad. Se dispone de una prueba diagnóstica con las siguientes características:

### a) si una persona está enferma, la prueba da positiva con probabilidad $0.95$;
### b) si una persona no está enferma, la prueba da positiva con probabilidad $0.08$.

### Si se elige una persona al azar y su prueba resulta positiva, ¿cuál es la probabilidad de que realmente esté enferma?

La probabilidad no sería tan cercana a 1 debido a que la muestra es muy pequeña (1%)

## Ejemplo 2.2.3


### Considérese una base de datos de pasajeros del Titanic. Sean los eventos:

### $A$: “el pasajero sobrevivió”;
### $B$: “el pasajero es mujer y viaja en primera clase”.

### La probabilidad condicional $\mathbb P(A\mid B)$ puede estimarse mediante la frecuencia relativa dentro de la base de datos, es decir, restringiendo el análisis únicamente a los registros que cumplen la condición $B$.

In [8]:
import seaborn as sns

data_titanic=sns.load_dataset('titanic')
data_titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [9]:
casos = data_titanic[(data_titanic['sex'] == 'female') & (data_titanic['class'] == 'First')]
casos.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
52,1,1,female,49.0,1,0,76.7292,C,First,woman,False,D,Cherbourg,yes,False

In [10]:
sum(casos['survived'])/len(casos['survived'])

0.9680851063829787

In [11]:
casos2 = data_titanic[(data_titanic['sex'] == 'male') & (data_titanic['class'] == 'Third')]
casos2.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [12]:
sum(casos2['survived'])/len(casos2['survived'])

0.13544668587896252

### ACTIVIDAD 2.2.4

#### Se selecciona al azar una persona de la población formada por habitantes de Puebla o Veracruz. Calcular la probabilidad de que la persona seleccionada sea de Puebla.