# Prueba de Hipótesis

### Una prueba de hipótesis es descrita por las siguientes componentes:
$\begin{align}
(X_1, \ldots, X_n; H_0, H_1; G)
\end{align}$
### donde $X_1, \ldots, X_n$ es una muestra aleatoria, $H_0$ y $H_1$ son hipótesis concernientes a la distribución de probabilidad de la población, y $G$ es un subconjunto de $\mathbb{R}^n$.

### El conjunto $G$ se denomina región crítica o de rechazo. Si $(X_1=x_1, X_2=x_2, \ldots, X_n=x_n)\in G\subset \mathbb{R}^n$ entonces se acepta $H_1$ en caso contrario se acepta $H_0$.

### $\textbf{Ejemplo}$ Considere el siguiente juego de hipótesis
$\begin{align}
H_0: X\sim N(500, 50)
\end{align}
\begin{align}
H_1: X\sim N(490, 50)
\end{align}$

### equivalentemente, $H_0:\mu=500$ vs $H_1:\mu=490$.

### Regla de Decisión: Si $X_1, X_2\leq 496$ entonces aceptamos $H_1$, i.e. $G=\{(x_1, x_2)\in \mathbb{R}^2:x_1,x_2\leq 496\}$.

<img src="cuadrohip.png">

### Hipótesis Unilateral/Bilateral.

### Los posibles escenarios al realizar una prueba de hipótesis son los siguientes:

<img src="cuadro-error.png">

## Contrastes de hipótesis para el parámetro $\mu$ de una variable normal con $\sigma$ conocida

### $H_0:\mu=\mu_0$ vs $H_1:\mu> \mu_0$

### Estadístico:
$\begin{align}
Z=\frac{\bar{X}-\mu}{\sigma/\sqrt{n}}\sim N(0,1)
\end{align}$

### La regla consistirá en rechazar $H_0$ si el estadístico de contraste $Z$ es mayor a un umbral ($z$) por determinar, el cual se obtiene vía el nivel de significancia ($\alpha$).

\begin{align}
\alpha=P(Z>z)\Longleftrightarrow 1-\alpha=P(Z\leq z).
\end{align}

### es decir, $z=z_{1-\alpha}$.

<img src="r1.png">

### En conclusión, Rechazar $H_0$, si el estadístico de contraste
\begin{align}
Z_0=\frac{\bar{X}-\mu_0}{\sigma/\sqrt{n}}>z_{1-\alpha}
\end{align}

### Observe que también queda determinado un intervalo de confianza para $\mu$:

$$Z<z_{1-\alpha}\Longrightarrow \frac{\bar{X}-\mu}{\sigma/\sqrt{n}}<z_{1-\alpha}$$

$$\mu\in (\bar{X}-z_{1-\alpha}\frac{\sigma}{\sqrt{n}}, \infty)$$

## El $p$-valor

### El $p$-valor es la probabilidad, calculada bajo la hipótesis nula, de obtener un valor del estadístico de prueba tan extremo o más extremo que el observado, en la dirección establecida por la hipótesis alternativa. En el caso anterior se tendría:

\begin{align}
p=\mathbb{P}(Z\geq Z_0|H_0)
\end{align}

##  El método de los seis pasos

### 1. Establecer la hipótesis nula $H_0$ y la hipótesis alternativa $H_1$.

### 2. Fijar un nivel de significacia $\alpha$.

### 3. Seleccionar el estadístico de contraste apropiado.

### 4. Calcular el valor del estadístico de contraste $Z_0$ a partir de los datos muestrales.

### 5. Calcular el $p$-valor del contraste.

### 6. Decisión: rechazar $H_0$ en favor de  $H_1$ si el $p$-valor es más pequeño que $\alpha$; en caso contrario, aceptar $H_0$.

## 8.2 Contrastes de hipótesis para el parámetro $\mu$ de una variable normal con $\sigma$ desconocida

### En este caso debemos considerar al estadístico $T$:
$$ T=\frac{\bar{X}-\mu}{\frac{S}{\sqrt{n}}}\sim T-Student(n-1)$$

### $\textbf{Ejemplo 8.2.1}$ Se espera que el nivel de colesterol en un grupo de pacientes bajo un determinado tratamiento se distribuya normalmente con media 220 mg/dl.

### Se toma una muestra de 9 pacientes, y se miden sus niveles: 203, 229, 215, 220, 223, 233, 208, 228,209.
### Contrastar la hipótesis que esta muestra efectivamente proviene de una población con media 220 mg/dl.
$H_0: \mu=220$ vs $H_1:\mu \neq 220$.

In [1]:
import numpy as np

colesterol=np.array([203, 229, 215, 220, 223, 233, 208, 228, 209])
media_muestral=np.mean(colesterol)
desv_muestral=np.std(colesterol, ddof=1)  
n=len(colesterol)
estadistico_contraste=(media_muestral - 220) / (desv_muestral / np.sqrt(n))
estadistico_contraste

np.float64(-0.38009147051646663)

In [2]:
import scipy.stats as stats
2*(1-stats.t.cdf(abs(estadistico_contraste), df=8))

np.float64(0.7137700471397654)

In [7]:
from scipy.stats import ttest_1samp
ttest_1samp(colesterol, popmean=220, alternative='two-sided')

TtestResult(statistic=np.float64(-0.38009147051646663), pvalue=np.float64(0.7137700471397654), df=np.int64(8))

### **Conclusión:** Como el $p$-valor $=0.7138>0.05$, no se rechaza $H_0$. Por lo tanto, no existe evidencia estadística suficiente para afirmar que el nivel medio de colesterol en plasma sea diferente de 220 mg/dl.

In [3]:
import seaborn as sns
iris=sns.load_dataset('iris')

### $\textbf{Ejemplo 8.2.2}$ Dada una muestra de tamaño 40 de flores de la tabla de datos iris, podemos considerar que la media de la longitud del sépalo es mayor que 5.7.

In [9]:
flores_elegidas=iris.sample(40, replace=True)
flores_elegidas

     sepal_length  sepal_width  petal_length  petal_width     species
66            5.6          3.0           4.5          1.5  versicolor
23            5.1          3.3           1.7          0.5      setosa
105           7.6          3.0           6.6          2.1   virginica
138           6.0          3.0           4.8          1.8   virginica
45            4.8          3.0           1.4          0.3      setosa
0             5.1          3.5           1.4          0.2      setosa
80            5.5          2.4           3.8          1.1  versicolor
46            5.1          3.8           1.6          0.2      setosa
140           6.7          3.1           5.6          2.4   virginica
37            4.9          3.6           1.4          0.1      setosa
122           7.7          2.8           6.7          2.0   virginica
24            4.8          3.4           1.9          0.2      setosa
127           6.1          3.0           4.9          1.8   virginica
13            4.3          3.0           1.1          0.1      setosa
141           6.9          3.1           5.1          2.3   virginica
50            7.0          3.2           4.7          1.4  versicolor
69            5.6          2.5           3.9          1.1  versicolor
104           6.5          3.0           5.8          2.2   virginica
144           6.7          3.3           5.7          2.5   virginica
34            4.9          3.1           1.5          0.2      setosa
56            6.3          3.3           4.7          1.6  versicolor
10            5.4          3.7           1.5          0.2      setosa
63            6.1          2.9           4.7          1.4  versicolor
8             4.4          2.9           1.4          0.2      setosa
21            5.1          3.7           1.5          0.4      setosa
125           7.2          3.2           6.0          1.8   virginica
84            5.4          3.0           4.5          1.5  versicolor
88            5.6          3.0           4.1          1.3  versicolor
10            5.4          3.7           1.5          0.2      setosa
55            5.7          2.8           4.5          1.3  versicolor
62            6.0          2.2           4.0          1.0  versicolor
58            6.6          2.9           4.6          1.3  versicolor
10            5.4          3.7           1.5          0.2      setosa
25            5.0          3.0           1.6          0.2      setosa
73            6.1          2.8           4.7          1.2  versicolor
60            5.0          2.0           3.5          1.0  versicolor
139           6.9          3.1           5.4          2.1   virginica
52            6.9          3.1           4.9          1.5  versicolor
141           6.9          3.1           5.1          2.3   virginica
124           6.7          3.3           5.7          2.1   virginica

In [10]:
long_sepalo_muestra=flores_elegidas['sepal_length'].values
long_sepalo_muestra

array([5.6, 5.1, 7.6, 6. , 4.8, 5.1, 5.5, 5.1, 6.7, 4.9, 7.7, 4.8, 6.1,
       4.3, 6.9, 7. , 5.6, 6.5, 6.7, 4.9, 6.3, 5.4, 6.1, 4.4, 5.1, 7.2,
       5.4, 5.6, 5.4, 5.7, 6. , 6.6, 5.4, 5. , 6.1, 5. , 6.9, 6.9, 6.9,
       6.7])

### Prueba T de una muestra

In [11]:
mu=5.7
ttest_1samp(long_sepalo_muestra, mu, alternative='greater')

TtestResult(statistic=np.float64(1.2423241956928965), pvalue=np.float64(0.1107677477637001), df=np.int64(39))

### **Conclusión:** Como el $p$-valor $=0.1319>0.05$, no se rechaza $H_0$. Por lo tanto, no existe evidencia estadística suficiente para afirmar que la longitud media poblacional del sépalo de las flores Iris sea mayor que 5.7 cm.

### $\textbf{Ejemplo 8.2.3}$ Consideremos la siguiente base de datos. Dicha tabla de datos contiene información acerca de 189 recién nacidos en cierto hospital en el año 1986.

In [12]:
import pandas as pd
datanac=pd.read_csv('datos\\data-birth.csv')
datanac.head()

   low  age  lwt  race  smoke  ptl  ht  ui  ftv   bwt
0    0   19  182     2      0    0   0   1    0  2523
1    0   33  155     3      0    0   0   0    3  2551
2    0   20  105     1      1    0   0   0    1  2557
3    0   21  108     1      1    0   0   1    2  2594
4    0   18  107     1      1    0   0   1    0  2600

Vamos a contrastar si la proporción de madres fumadoras supera el 30%:

$H_0:$ $p=0.3$

$H_1:$ $p>0.3$

In [13]:
madres_elegidas=datanac.sample(30, replace=True)
madres_elegidas

     low  age  lwt  race  smoke  ptl  ht  ui  ftv   bwt
135    1   27  150     3      0    0   0   0    0  1588
123    0   22  129     1      0    0   0   0    0  4111
104    0   20  120     3      0    0   0   0    0  3770
112    0   29  130     1      1    0   0   0    2  3884
160    1   17  110     1      1    0   0   0    0  2225
46     0   32  132     1      0    0   0   0    4  3080
161    1   25  105     3      0    1   0   0    1  2240
37     0   27  124     1      1    0   0   0    0  2922
135    1   27  150     3      0    0   0   0    0  1588
131    1   29  130     1      0    0   0   1    2  1021
19     0   28  120     1      1    0   0   0    1  2821
106    0   30  112     1      0    0   0   0    1  3799
181    1   20  105     3      0    0   0   0    3  2450
15     0   18  100     1      1    0   0   0    0  2769
182    1   26  190     1      1    0   0   0    0  2466
97     0   19  147     1      1    0   0   0    0  3651
119    0   16   95     3      0    0   0   0    1  3997
175    1   30  142     1      1    1   0   0    0  2410
187    1   17  142     2      0    0   1   0    0  2495
38     0   31  215     1      1    0   0   0    2  3005
79     0   23  190     1      0    0   0   0    0  3459
131    1   29  130     1      0    0   0   1    2  1021
81     0   32  170     1      0    0   0   0    0  3473
154    1   24  138     1      0    0   0   0    0  2100
42     0   23  130     2      0    0   0   0    1  3062
67     0   28  250     3      1    0   0   0    6  3303
161    1   25  105     3      0    1   0   0    1  2240
174    1   23  120     3      0    0   0   0    0  2410
162    1   20  109     3      0    0   0   0    0  2240
37     0   27  124     1      1    0   0   0    0  2922

In [14]:
numero_madres_fumadoras=np.sum(madres_elegidas['smoke'] == 1)
numero_madres_fumadoras

np.int64(11)

In [ ]:
from scipy.stats import binomtest
# datos, tamaño muestra, el valor de la H_0, tipo de prueba
binomtest(numero_madres_fumadoras, 30, p=0.3, alternative='greater')

BinomTestResult(k=11.0, n=30.0, alternative='greater', statistic=0.36666666666666664, pvalue=0.2696296136972765)

Conclusión: Dada la muestra no es posible rechazar la hipóteis nula. Es decir, no hay evidencia suficiente para rechazar que la proporción de madres fumadoras es o.3.

## Contrastes de hipótesis para el parámetro $\sigma$ de una variable con distribución normal

### En el caso de hipótesis referente a la varianza (desviación estandar) de una población se utiliza el estadístico:
$$ \chi^2_{n-1}=\frac{(n-1)S^2}{\sigma^2}$$
### el cual tiene una distribución $\chi^2$ con n-1 grados de libertad.

### $\textbf{Ejemplo}$ Verifiquemos que si la varianza de la amplitud del sépalo de las flores de la base de datos iris es menor que 0.2. Considere un nivel de significancia de 0.05.
### $H_0:\sigma^2= 0.2$ vs $H_1=\sigma^2< 0.2$

In [13]:
from scipy.stats import chi2

flores_elegidas_chi=iris.sample(40, replace=False)

varianza_muestral=flores_elegidas_chi['sepal_width'].var()
n=len(flores_elegidas_chi)
varianza_hipotetica=0.2
estadistico_prueba=(n - 1) * varianza_muestral / varianza_hipotetica

valor_critico=chi2.ppf(0.05, df=n-1)  
print(valor_critico)
print(estadistico_prueba)

25.695390399574777
55.495000000000005

### **Conclusión:** Como el estadístico de prueba $\chi^2_{\mathrm{obs}}=55.4950$ es mayor que el valor crítico $\chi^2_{\mathrm{crítico}}=25.6954$, no se rechaza $H_0$ al nivel de significancia del 5%. Por lo tanto, no existe evidencia estadística suficiente para afirmar que la varianza poblacional de la anchura del sépalo de las flores Iris sea menor que 0.2 cm².

### Ejercicio: Elaborar el código para concluir la prueba en base al p-valor.