<h2>Handling Categorical Variables</h2>
<div style="text-align: justify">
Categorical variables are used to represent groups or categories that are qualitative in nature. Some examples are survey responses like marital status, profession or educational qualifications. While these can easily be understood by a human, some problems can arise with categorical data and they must be dealt with before proceeding with any other task.
To get from qualitative inputs to quantitative features, one may naively think that assigning every category in a column a number would suffice, but categories are unordered, so assigning this order may greatly penalize the effectiveness of your model.

<h2>Encoding categorical features</h2>
Certain learning algorithms like regression and neural networks require their input to be numbers. Hence, categorical data must be converted to numbers to use these algorithms.<br>
<h3>One-hot encoding</h3>
One-hot encoding converts n categories into n features. You can use the get_dummies() function to one-hot encode columns. The function takes a DataFrame and a list of categorical columns you want converted into one hot encoded columns, and returns an updated DataFrame with these columns included.

<h3>Dummy encoding</h3>
Dummy encoding creates n-1 features for n categories, omitting the first category. For dummy encoding, you can use the same get_dummies() function with an additional argument, drop_first set to True.<br>
Both these methods have different advantages. One-hot encoding generally creates much more explainable features, but one must be aware that one hot encoding may create features that are entirely collinear due to the same information being represented multiple times.<br>
Both one-hot encoding and dummy encoding may result in a huge number of columns being created if there are too many different categories in a column. In these cases, you may want to only create columns for the most common values. You can check the number of occurrences of different features in a column using the value_counts() method on a specific column.
</div>

In [2]:
import pandas as pd
data=pd.DataFrame({"country":["Mexico","USA","Canada","USA"],"gender":["F","F","M","M"]})
display(data)
pd.get_dummies(data,columns=["country","gender"],prefix=["c","g"],dtype=int)

  country gender
0  Mexico      F
1     USA      F
2  Canada      M
3     USA      M

   c_Canada  c_Mexico  c_USA  g_F  g_M
0         0         1      0    1    0
1         0         0      1    1    0
2         1         0      0    0    1
3         0         0      1    0    1

In [ ]:
#activity:. apply one encoding for gender in employees dataset.
#Apply dummy enconding and find employees which are females.