In [1]:
import numpy as np
import pandas as pd

In [4]:
datos = pd.DataFrame({
    'hours_sleep':[1,2,3,4,5,6,7],
    'attendance':[60,65,70,75,80,85,87],
    'grades':[50,65,70,75,np.nan,85,np.nan]
})

datos

   hours_sleep  attendance  grades
0            1          60    50.0
1            2          65    65.0
2            3          70    70.0
3            4          75    75.0
4            5          80     NaN
5            6          85    85.0
6            7          87     NaN

In [7]:
from sklearn.linear_model import LinearRegression

In [15]:
train_df = datos[datos['grades'].notnull()]
train_df
missing_df = datos[datos['grades'].isnull()]
missing_df
x_train = train_df[['hours_sleep', 'attendance']]
y_train = train_df['grades']

#fit regression
modelo = LinearRegression()
modelo.fit(x_train,y_train)

x_test = missing_df[['hours_sleep', 'attendance']]
predict = modelo.predict(x_test)
predict

array([80.67567568, 89.90644491])

In [ ]:
# single imputation
data_filled = datos.copy()
data_filled.loc[data_filled['grades'].isnull(), 'grades'] = predict
data_filled

   hours_sleep  attendance     grades
0            1          60  50.000000
1            2          65  65.000000
2            3          70  70.000000
3            4          75  75.000000
4            5          80  80.675676
5            6          85  85.000000
6            7          87  89.906445

In [18]:
#bayesian regression
from sklearn.linear_model import BayesianRidge

In [25]:
train_df = datos[datos['grades'].notnull()]
missing_df = datos[datos['grades'].isnull()]
x_train = train_df[['hours_sleep', 'attendance']]
y_train = train_df['grades']

bayesian_model = BayesianRidge()
bayesian_model.fit(x_train, y_train)

x_test = missing_df[['hours_sleep', 'attendance']]
predict2 = bayesian_model.predict(x_test)
predict2

#computing the uncertanties
predict2, std = bayesian_model.predict(x_test, return_std=True)

# print(predict2 , std)
for predict, uncert in zip(predict2, std):
    print('predict', predict)
    print('uncertanty', uncert)

predict 80.45396941441557
uncertanty 3.789951707447654
predict 89.50945805401761
uncertanty 4.529439480000733

In [51]:
# challenge:
# generate differente values for imputation

aleatorios1 = np.random.normal(loc=predict2[0], scale=std.iloc[0], size=100)
aleatorios2 = np.random.normal(loc=predict2[1], scale=std.iloc[1], size=100)