<h1>Data profiling</h1>
   <div style="text-align: justify"> Data profiling is the process of reviewing and cleaning data to understand how data’s structure and maintain data quality standards. The main purpose is to gain insight into the quality of the data by using methods to review and summarize it, and then evaluating its condition.
Data profiling evaluates data based on factors such as accuracy, consistency, and timeliness to show if the data is lacking consistency or accuracy or has null values. Data profiling can be an important precursor to data processing and data analytics.<br>
Pandas Profiling is used to generate a complete and exhaustive report for the dataset, with many features and customizations in the generated report. This report includes various pieces of information such as dataset statistics, distribution of values, missing values, memory usage, etc., which are very useful for exploring and analyzing data efficiently.
</div>

In [ ]:
#importing pandas profiling library
!pip install ydata-profiling

Collecting ydata-profiling
  Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.2.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.13.4)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.0.2)
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling)
  Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.6.0)
Collecting imagehash==4.3.2 (from ydata-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.9.6)
Collecting dacite<2,>=1.9 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (26.3)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->ydata-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2026.3)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.7.22)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-2.2.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.8/400.8 kB 13.6 MB/s eta 0:00:00
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 20.7 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 63.2 MB/s eta 0:00:00
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (679 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 30.1 MB/s eta 0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 6.0 MB/s eta 0:00:00
Downloading puremagic-2.2.0-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 5.4 MB/s eta 0:00:00
Installing collected packages: minify-html, filetype, puremagic, multimethod, dacite, imagehash, visions, phik, ydata-profiling
Successfully installed dacite-1.9.2 filetype-1.2.0 imagehash-4.3.2 minify-html-0.18.1 multimethod-1.12 phik-0.12.5 puremagic-2.2.0 visions-0.8.1 ydata-profiling-4.18.4

<div style="text-align: justify">The pandas profiling library in Python includes a method named as ProfileReport() which generates a basic report on the input DataFrame.

The report consists of the following:<br>
- DataFrame overview<br>
- Each attribute on which DataFrame is defined<br>
- Correlations between attributes (Pearson Correlation and Spearman Correlation)<br>
- A sample of DataFrame.<br>
</div>

In [ ]:
#Data profiling Report
ProfileReport(df, **kwargs)

The arguments are:<br>
![image.png](attachment:image.png)

For generating the profile report we use the Profile Report

In [ ]:
import pandas as pd
my_dat=pd.read_csv('SSNMX.csv',skiprows=4,skipfooter=7, engine='python')

In [ ]:
from ydata_profiling import ProfileReport
profile=ProfileReport(my_dat)
profile.to_notebook_iframe()

/tmp/ipykernel_1265/3244056840.py:1: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]
 10%|█         | 1/10 [00:00<00:02,  3.35it/s]
 50%|█████     | 5/10 [00:00<00:00, 15.00it/s]
 80%|████████  | 8/10 [00:00<00:00, 15.14it/s]
100%|██████████| 10/10 [00:00<00:00, 11.95it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
my_dat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2171 entries, 0 to 2170
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Fecha                       2171 non-null   object
 1   Hora                        2171 non-null   object
 2   Magnitud                    2171 non-null   object
 3   Latitud                     2171 non-null   float64
 4   Longitud                    2171 non-null   float64
 5   Profundidad                 2171 non-null   float64
 6   Referencia de localizacion  2171 non-null   object
 7   Fecha UTC                   2171 non-null   object
 8   Hora UTC                    2171 non-null   object
 9   Estatus                     2171 non-null   object
dtypes: float64(3), object(7)
memory usage: 169.7+ KB

In [ ]:
my_dat['Magnitud'].value_counts()

Magnitud
no calculable    1927
4.5                18
4.7                15
2.5                14
4.6                14
2.4                12
4.4                12
4.3                12
4.2                11
2.6                11
4.9                 9
3.8                 9
3.9                 9
4.8                 8
5.1                 7
4.1                 7
2.8                 7
2.3                 7
4.0                 7
3.6                 6
5.2                 6
2.7                 6
2.2                 6
5.0                 5
3.0                 5
3.5                 4
5.3                 3
3.7                 3
3.2                 2
5.6                 2
3.1                 1
2.9                 1
2.1                 1
5.4                 1
5.9                 1
8.1                 1
7.6                 1
Name: count, dtype: int64

In [ ]:
my_dat['Magnitud'] = pd.to_numeric(my_dat['Magnitud'], errors='coerce')
my_dat['Magnitud']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
2166   NaN
2167   NaN
2168   NaN
2169   NaN
2170   NaN
Name: Magnitud, Length: 2171, dtype: float64

In [ ]:
profile=ProfileReport(my_dat)
profile.to_notebook_iframe()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]
 10%|█         | 1/10 [00:00<00:02,  3.98it/s]
 20%|██        | 2/10 [00:00<00:02,  3.03it/s]
 70%|███████   | 7/10 [00:00<00:00, 11.55it/s]
100%|██████████| 10/10 [00:01<00:00,  5.74it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

algunas funciones importantes

dropna() elimina las filas que tengan un n.a; argumentos
thresh, limitm inplace

fillna()
method

isnull()

notnull()

In [ ]:
funciona_dropna = my_dat.fillna()
funciona_dropna

,Fecha,Hora,Magnitud,Latitud,Longitud,Profundidad,Referencia de localizacion,Fecha UTC,Hora UTC,Estatus
0,1985-01-01,00:51:59,hola,15.90,-98.72,33.0,"86 km al SUROESTE de PINOTEPA NACIONAL, OAX",1985-01-01,06:51:59,revisado
1,1985-01-01,01:08:39,hola,17.98,-102.00,33.0,"22 km al ESTE de CD LAZARO CARDENAS, MICH",1985-01-01,07:08:39,revisado
2,1985-01-01,07:12:01,hola,15.70,-94.27,33.0,"70 km al SUROESTE de TONALA, CHIS",1985-01-01,13:12:01,revisado
3,1985-01-01,08:25:34,hola,15.35,-94.51,33.0,"115 km al SUROESTE de TONALA, CHIS",1985-01-01,14:25:34,revisado
4,1985-01-01,10:55:11,hola,16.13,-98.37,33.0,"41 km al SUROESTE de PINOTEPA NACIONAL, OAX",1985-01-01,16:55:11,revisado
...,...,...,...,...,...,...,...,...,...,...
2166,1985-12-31,02:03:03,hola,15.27,-93.19,33.0,"37 km al SUROESTE de MAPASTEPEC, CHIS",1985-12-31,08:03:03,revisado
2167,1985-12-31,06:14:12,hola,17.09,-101.79,16.0,"66 km al SUROESTE de ZIHUATANEJO, GRO",1985-12-31,12:14:12,revisado
2168,1985-12-31,17:11:30,hola,18.11,-93.72,33.0,"38 km al NOROESTE de CARDENAS, TAB",1985-12-31,23:11:30,revisado
2169,1985-12-31,21:51:24,hola,16.70,-98.02,9.0,"40 km al NORTE de PINOTEPA NACIONAL, OAX",1986-01-01,03:51:24,revisado
2170,1985-12-31,22:57:01,hola,15.89,-93.49,33.0,"36 km al SURESTE de TONALA, CHIS",1986-01-01,04:57:01,revisado

<h1>Profiling Large Datasets</h1>
<div style="text-align: justify"> For small datasets, ydata-profiling computations can be performed quickly. However, for larger datasets, it may become too unwieldy.<br>
ydata-profiling includes a minimal configuration file where the most expensive computations are turned off by default. This configuration excludes time-consuming sections such as correlations and interactions.
</div>

In [ ]:
#Minimal configurations
report = ProfileReport(my_dat,minimal=True)
report
#profile.to_file("output.html")

An alternative way to **handle really large datasets** is to use a portion of it to generate the profiling report. Several users report this is a good way to scale back the computation time while maintaining representativity.

In [ ]:
#Sampling
sample = my_dat.sample(1000)
profile = ProfileReport(sample, minimal=True)
profile

<h1>Note on Primary and secondary data</h1>
<div style="text-align: justify">Data that has been collected from first-hand-experience is known as **primary data**. Primary data has not been published yet and is more reliable, authentic and objective. Primary data has not been changed or altered.<br>
Data collected from a source that has already been published in any form is called as **secondary data**. The review of literature in any research is based on secondary data. It is collected by someone else for some other purpose.
</div>

<h1>Note on Data Management</h1>
<div style="text-align: justify">Data management (DM) is the process of managing the way data is collected, processed, analyzed, preserved, and published. It’s about making all the materials findable, organized, documented, and safe, while also making the analysis process as efficient as possible.
</div>

<h1>Note on correlation</h1>
Correlation is a statistical measure that expresses the extent to which two variables are linearly related (meaning they change together). It’s a common tool for describing simple relationships without making a statement about cause and effect.
Finding Relationships is a great aspect of the Pandas module. In Pandas we have the corr() method. The corr() method calculates the relationship between each column in your data set. Note: The corr() method ignores "not numeric" columns.<br>
The Result of the corr() gives numbers that vary from -1 to 1. 1 means that there is a 1 to 1 relationship (a perfect correlation), and for this data set, each time a value went up in the first column, the other one went up as well. -0.9 would be just as good relationship as 0.9, but if you increase one value, the other will probably go down.
Note: Correlation coefficients whose magnitude are between 0.9 and 1.0 indicate variables which can be considered very highly correlated. Correlation coefficients whose magnitude are between 0.7 and 0.9 indicate variables which can be considered highly correlated.

In [ ]:
#Download Hubble database
hubble_vd.corr()
hubble_vd.plot(kind="scatter",x="distance",y="velocity")